// Generated by cpp11: do not edit by hand


#include "cpp11/declarations.hpp"

// shaping.cpp
void test();
extern "C" SEXP _stringshaper_test() {
  BEGIN_CPP11
    test();
    return R_NilValue;
  END_CPP11
}

extern "C" {
/* .Call calls */
extern SEXP _stringshaper_test();

static const R_CallMethodDef CallEntries[] = {
    {"_stringshaper_test", (DL_FUNC) &_stringshaper_test, 0},
    {NULL, NULL, 0}
};
}

extern "C" void R_init_stringshaper(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
