# Generated by cpp11: do not edit by hand

get_string_shape_c <- function(string, id, path, index, features, size, res, lineheight, align, hjust, vjust, width, tracking, indent, hanging, space_before, space_after, direction, soft_wrap, hard_wrap) {
  .Call(`_textshaping_get_string_shape_c`, string, id, path, index, features, size, res, lineheight, align, hjust, vjust, width, tracking, indent, hanging, space_before, space_after, direction, soft_wrap, hard_wrap)
}

get_line_width_c <- function(string, path, index, size, res, include_bearing, features) {
  .Call(`_textshaping_get_line_width_c`, string, path, index, size, res, include_bearing, features)
}
